name: Deploy Three-Tier App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      - name: Copy files to VM
        run: |
          scp -o StrictHostKeyChecking=no -r . azureuser@4.232.186.60:/home/azureuser/app

      - name: Deploy on Azure VM
        run: |
            ssh -o StrictHostKeyChecking=no azureuser@4.232.186.60 "
            cd /home/azureuser/app &&
            sudo docker-compose down &&
            sudo docker-compose up -d --build
          "
